name: Deafhood
favicon: null
layout_spectrum: 0.4871384578291327
typography_spectrum: 0.6885095243342221
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.22569281607866287
  lightness: 0.2755821500904858
  saturation: 0.6217050971463323
  rhythmicContrast: 0.47588214348070323
purpose: []
